### ISSUE TITLE
Wrong Swagger path in config/params.php

### ISSUE THREAD

**Issue by nkondrashov** [yiisoft/yii-debug-api#133]
In file `config/params.php` wrong way for `yiisoft/yii-swagger`

### What steps will reproduce the problem?
Open Swagger UI in demo apps

### What is the expected result?
Correct `annotation-paths` for `yiisoft/yii-swagger`

### What do you get instead?
`500: "yii-debug-api/src/Controller" directory does not exist.`

### Additional info

| Q                | A
| ---------------- | ---
| Version          |  master
| PHP version      |  8.1
| Operating system |

**Comment by samdark** [comment]
Do you have time for a pull request?
