### ISSUE TITLE
Unnecessary JSON encode/decode

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-debug-api#55]
`VarDumper` create [JSON string](https://github.com/yiisoft/var-dumper/blob/c2c465ba8b8eea53becae2a00fe410246e2f7c00/src/VarDumper.php#L157) by use `json_enode`:

```php
return json_encode($output, JSON_THROW_ON_ERROR);
```

Then in this package [used](https://github.com/yiisoft/yii-debug-api/blob/491c69cd42b31e56ab404e06c0905f2dcbeabfac/src/Controller/InspectController.php#L37-L38) `json_decode` for result:

```php
$response = VarDumper::create($data)->asJson(false, 255);
return $this->responseFactory->createResponse(json_decode($response));
```

It doesn't look good. May be add method to `VarDumper` that return raw JSON ?

**Comment by xepozz** [comment]
https://github.com/yiisoft/var-dumper/pull/75
